cnp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from log.forms import LoginForm

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^newsite/', include('newsite.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^nodeb/', include('nodeb.urls')),
    url(r'^process/', include('process.urls')),
    url(r'^igw/', include('igw.urls')),
    url(r'', include('log.urls')),
    url(r'^login/', auth_views.login, name='login', kwargs={'template_name': 'log/login.html', 'authentication_form': LoginForm}),
    url(r'^logout/', auth_views.logout, name='logout', kwargs={'next_page': '/login'} ),
]

nodeb/urls.py
from django.conf.urls import url
from .views import NodebPlan, ImportExport, NodebAjax, About, Search, Download

app_name = 'nodeb'
urlpatterns = [
    url(r'^$', NodebPlan.as_view(), name='nodeb-plan'),
    url(r'^nodebajax/$', NodebAjax.as_view(), name='nodebajax'),
    url(r'^io/$', ImportExport.as_view(), name='io'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^search/$', Search.as_view(), name='search'),
    url(r'^download/(?P<type>[a-z]+)/$', Download.as_view(), name='download')
]

nodeb/models.py
from django.db import models

class Ucell( models.Model ):
    sitename = models.CharField(max_length=500)
    rncname = models.CharField(max_length=500)
    lac = models.IntegerField(default=0)
    rac = models.IntegerField(default=0)
    plmn = models.CharField(max_length=500, default='')
    ura = models.IntegerField(default=0)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)

    def __str__(self):
        return self.sitename


# meta information
# e.g who saves Gcell and When it is saved etc
class SiteMeta(models.Model):
    meta_key = models.CharField(max_length=500, default=None, blank=True, null=True)
    meta_value = models.CharField(max_length=500, default=None, blank=True, null=True)
    remarks = models.CharField(max_length=500, default=None, blank=True, null=True)


#RNC info
class HwRNC(models.Model):
    rncname = models.CharField(max_length=500)
    vendor = models.CharField(max_length=500)
    subrack_slot = models.CharField(max_length=500)
    board = models.CharField(max_length=500)
    port_number = models.IntegerField(default=0)
    main_address = models.CharField(max_length=500, default=None)
    subnet_mask = models.CharField(max_length=500, default=None)
    gateway_address = models.CharField(max_length=500, default=None)

    def __str__(self):
        return self.rncname


#Ericsson RNC information
class ERNC(models.Model):
    rncname = models.CharField(max_length=500)
    vendor = models.CharField(max_length=500)
    main_address = models.CharField(max_length=500, default=None)
    subnet_mask = models.CharField(max_length=500, default=None)
    gateway_address = models.CharField(max_length=500, default=None)

    def __str__(self):
        return self.rncname


#SPU information
class HwSPU(models.Model):
    rncname = models.CharField(max_length=500)
    vendor = models.CharField(max_length=500, default=None)
    spu_srn = models.IntegerField(default=55)
    spu_sn = models.IntegerField(default=55)
    sctp_link1 = models.IntegerField(default=1000)
    sctp_link2 = models.IntegerField(default=1001)

    def __str__(self):
        return self.rncname


#separate SPU informaiton for RNC6900
#This deb contains information of SPU info for all RNC6900
#6900 spu_srn, spu_sn, stcpt_link1 & sctp2 must be unique
#for 6901, sctp_link1 & sctp_line2 must be unique. we put a default value of 55 for both spu_srn & spu_sn
class OldHwSPU(models.Model):
    sitename = models.CharField(max_length=500)
    rncname = models.CharField(max_length=500)
    vendor = models.CharField(max_length=500, default=None)
    spu_srn = models.IntegerField(default=55)
    spu_sn = models.IntegerField(default=55)
    sctp_link1 = models.IntegerField(default=1000)
    sctp_link2 = models.IntegerField(default=1001)

    def __str__(self):
        return self.sitename



#saves initial site info and it will be shown later at about page
class NodebDatabase(models.Model):
    sitename = models.CharField(max_length=500)
    rncname = models.CharField(max_length=500)
    lac = models.IntegerField(default=0)
    rac = models.IntegerField(default=0)
    plmn_lac_min = models.CharField(max_length=500, default='')
    plmn_lac_max = models.CharField(max_length=500, default='')
    plmn_rac_min = models.CharField(max_length=500, default='')
    plmn_rac_max = models.CharField(max_length=500, default='')
    ura = models.IntegerField(default=0)
    subrack_slot = models.CharField(max_length=500)
    rnc_main_address = models.CharField(max_length=500, default=None)
    rnc_gateway_address = models.CharField(max_length=500, default=None)
    rnc_subnet_mask = models.CharField(max_length=500, default=None)
    board_port = models.CharField(max_length=500, default='')
    spu_srn = models.CharField(max_length=500, default='')
    spu_sn = models.CharField(max_length=500, default='')
    sctp_link1 = models.CharField(max_length=500, default='')
    sctp_link2 = models.CharField(max_length=500, default='')
    plan_date = models.DateField()
    username = models.CharField(default='NA', max_length=500)

    def __str__(self):
        return self.sitename


#latitude & longitude database
class LatLonDatabase(models.Model):
    sitename = models.CharField(max_length=500)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)

    def __str__(self):
        return self.sitename


#RNC SCTP Link Tracker
class RNCTracker(models.Model):
    sitename = models.CharField(max_length=500)
    rncname = models.CharField(max_length=500)
    rnc_ip = models.CharField(max_length=500)

    def __str__(self):
        return self.rncname

nodeb/forms.py
from django import forms

#hanling import and export of different files of nodeb
TYPES = (
    ('newucell', 'New Ucell'),
    ('ucell', 'Update Ucell'),
    ('spu', 'Update SPU'),
    #('newspu', 'New SPU')
)
class DataIO(forms.Form):
    file = forms.FileField()
    type = forms.ChoiceField(choices=TYPES, required=True)


#plan/lat-lon file uploader
class LatLonFileUploadForm(forms.Form):
    file = forms.FileField()
    plan_uploaded = forms.CharField(widget=forms.HiddenInput())

#Handle final plan download
class FinalPlanDonwloadForm(forms.Form):
    cnp_wr = forms.CharField(widget=forms.HiddenInput())
    ipwave_wr = forms.CharField(widget=forms.HiddenInput())
    site = forms.CharField(widget=forms.HiddenInput())
    rnc = forms.CharField(widget=forms.HiddenInput())
    lac = forms.CharField(widget=forms.HiddenInput())
    rac = forms.CharField(widget=forms.HiddenInput())
    plmn = forms.CharField(widget=forms.HiddenInput())
    ura = forms.CharField(widget=forms.HiddenInput())
    lat = forms.CharField(widget=forms.HiddenInput())
    lon = forms.CharField(widget=forms.HiddenInput())
    vendor = forms.CharField(widget=forms.HiddenInput())


#Search fileds in search page
class SearchSites(forms.Form):
    s = forms.CharField()




nodeb/views.py
from django.shortcuts import render
from django.views import View
from .forms import DataIO, LatLonFileUploadForm, FinalPlanDonwloadForm, SearchSites
from .helper import DataIOHelper, NodebPlanHelper, NodebAjaxHelper, SiteMetaHelper, LatLonDatabase, AboutHelper, SearchHelper, DownloadHelper
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
import django_excel as excel
from django.utils import timezone
from .models import HwSPU, NodebDatabase
from django.urls import reverse
import sys


#handles lat long file & allow downloading
class NodebPlan( LoginRequiredMixin, View ):
    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'
    context = {'title': 'CNP Plan: New 3G'}

    def get(self, request):
        form = LatLonFileUploadForm(initial={'plan_uploaded':'Y'})
        return render( request, 'nodeb/index.html', {'context': self.context, 'form': form} )


    #handle plan file upload
    def post(self, request):
        if request.POST.get('plan_uploaded') == 'Y' and request.FILES['file']:
            form = LatLonFileUploadForm(request.POST, request.FILES)
            if form.is_valid():
                data = NodebPlanHelper().process_latlong_file(request.FILES['file'])
            else:
                data = []
        else:

            try:
                PlanHelper = NodebPlanHelper() # instantiating Plan Helper

                header = ['WR Name', 'Site Name', 'RNC', 'LAC', 'RAC', 'PLMN Tag LAC Min', 'PLMN Tag LAC Max', 'PLMN Tag RAC Min', 'PLMN Tag RAC Max', 'URA ID', 'Subrack, Slot', 'RNC/BSC FG2C (Main) IP Address', 'Subnet mask RNC', 'BSC/RNC Gateway', 'FG2C PN', 'SPU SRN', 'SPU SN', 'SCTP LNKN 1', 'SCTP LNKN 2']
                d = [header]

                sites = request.POST.getlist('site')
                ipwave_wrs = request.POST.getlist('ipwave_wr')
                cnp_wrs = request.POST.getlist('cnp_wr')
                rncs = request.POST.getlist('rnc')
                lacs = request.POST.getlist('lac')
                racs = request.POST.getlist('rac')
                plmns = request.POST.getlist('plmn')
                uras = request.POST.getlist('ura')
                lats = request.POST.getlist('lat')
                lons = request.POST.getlist('lon')
                vendors = request.POST.getlist('vendor')

                for i in range(len(sites)):

                    rnc_info = PlanHelper.get_rnc_info(rncs[i], vendors[i])

                    if vendors[i].upper() == 'H':
                        plmn_lac_min = int(plmns[i])
                        plmn_lac_max = plmn_lac_min + 15
                        plmn_rac_min = plmn_lac_min + 16
                        plmn_rac_max = plmn_lac_min + 31

                        spu_info = PlanHelper.get_spu(rncs[i], rnc_info['vendor'])
                    else:
                        plmn_lac_min = ''
                        plmn_lac_max = ''
                        plmn_rac_min = ''
                        plmn_rac_max = ''
                        spu_info = { 'spu_srn': '', 'spu_sn': '', 'sctp_link1': '', 'sctp_link2': '' }


                    full_info = [ ipwave_wrs[i], sites[i], rnc_info['rncname'], lacs[i], racs[i], plmn_lac_min, plmn_lac_max, plmn_rac_min,
                             plmn_rac_max, uras[i], rnc_info['subrack_slot'], rnc_info['main_address'], rnc_info['subnet_mask'],
                             rnc_info['gateway_address'], rnc_info['port'], spu_info['spu_srn'], spu_info['spu_sn'], spu_info['sctp_link1'], spu_info['sctp_link2'] ]

                    d.append(full_info)

                    #updating spu info to adjust further
                    if vendors[i].upper() == 'H':
                        PlanHelper.update_spu_info(sites[i], spu_info)
                        PlanHelper.update_rnc_tracker(sites[i], rnc_info)

                    plan_date = "{:%Y-%m-%d}".format(timezone.now())
                    PlanHelper.save_at_nodeb_database(full_info, plan_date, request.user.username) #solving database
                    PlanHelper.save_latlong(sites[i], lats[i], lons[i]) #saving lat long file

                #naming attachments
                try:
                    attachment_name = "WR_" + cnp_wrs[0]
                except:
                    today_date = "{:%Y-%m-%d}".format(timezone.now())
                    attachment_name = "WR_" + today_date

                return excel.make_response_from_array(d, 'xls', file_name=attachment_name)
            except:
                print("Unexpected error:", sys.exc_info()[0])
                raise


        return render(request, 'nodeb/map.html', {'data': data, 'form': FinalPlanDonwloadForm, 'context': self.context})



#handle data e.g ucell data uploading
class ImportExport( LoginRequiredMixin, View ):
    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    #only page query
    def get(self, request):
        form = DataIO
        context = {'title': 'CNP 3G Plan: IO', 'form': form}
        return render(request, 'nodeb/io.html', {'context': context})

    #handle post requests ( ajax ) requests
    def post(self, request):
        form = DataIO(request.POST, request.FILES)
        data = {}
        if form.is_valid():
            if form.cleaned_data['type'] == 'ucell':
                data = DataIOHelper().save_ucell( request.FILES['file'], request )
                data['is_valid'] = True
                self.keep_log('ucell', 'mode: Ucell', request) #keeping log

            elif form.cleaned_data['type'] == 'spu':
                data = DataIOHelper().save_spu(request.FILES['file'], request, 'update')
                data['is_valid'] = True
                self.keep_log('spu', 'mode: HwSPU', request) #keeping log

            elif form.cleaned_data['type'] == 'newspu':
                data = DataIOHelper().save_spu(request.FILES['file'], request, 'new')
                data['is_valid'] = True
                self.keep_log('spu', 'mode: HwSPU', request) #keeping log

            elif form.cleaned_data['type'] == 'newucell':
                data = DataIOHelper().save_new_ucell( request.FILES['file'], request )
                data['is_valid'] = True
                self.keep_log('ucell', 'mode: Ucell', request)  # keeping log
            else:
                data['is_valid'] = False
        else:
            data['is_valid'] = False

        return JsonResponse(data)

    #keep track at site meta database
    def keep_log(self, type, comment, request = None):
        data = {
            'save_time': "{:%d-%m-%Y}".format(timezone.now()),
            'save_by': request.user.username
        }
        for key, value in data.items():
            SiteMetaHelper().save_log(type + '_' + key, value, comment)


#Handling ajax at plan page
class NodebAjax(View):
    def get(self, request):
        self.request = request
        if request.GET.get('hook') == 'nearestsites':
            limit = 100
            lat = request.GET.get('lat', None)
            lon = request.GET.get('lon', None)
            vendor = request.GET.get('vendor', None)
            data = NodebAjaxHelper().get_nearest_sites( lat, lon, vendor, limit);
        elif request.GET.get('hook') == 'recentplans':
            limit = 100
            data = NodebAjaxHelper().get_recent_plans(limit);
        else:
            data = []
        return JsonResponse(data, safe=False)  # default function to handle json form django 1.8


#About page
class About(View):
    def get(self, request):
        context = {
            'title': 'CNP 3G Plan: About',
            'ucell': AboutHelper().get_ucell_info(),
            'spu': AboutHelper().get_spu_info(),
        }
        return render(request, 'nodeb/about.html', {'context': context})


#Search page
class Search(View):
    def get(self, request):

        if request.is_ajax():
            data = []
            if request.GET.get('hook', None) == 'search':
                form = SearchSites(request.GET)
                if form.is_valid():
                    limit = 350
                    data = SearchHelper().get_nearest_sites( form.cleaned_data['s'].strip(), limit )

            return JsonResponse(data, safe=False)

        else:
            context = {
                'title': 'CNP 3G Plan: Search',
                'form': SearchSites
            }
            return render(request, 'nodeb/search.html', {'context': context})


# Download links
class Download(View):
    def get(self, request, type=None):
        download_date = "{:%Y-%m-%d}".format(timezone.now())
        if type == 'spu':
            #data = DownloadHelper().get_whole_spu()
            data = DownloadHelper().get_whole_old_spu()
            return excel.make_response_from_array(data, 'xlsx', file_name='SPU_DB_' + download_date)
        elif type == 'latlon':
            data = DownloadHelper().get_whole_latlon()
            return excel.make_response_from_array(data, 'xlsx', file_name='LatLon_DB_' + download_date)
        elif type == 'ucell':
            data = DownloadHelper().get_whole_ucell()
            return excel.make_response_from_array(data, 'xlsx', file_name='UCELL_' + download_date)
        else:
            return HttpResponseRedirect(reverse('nodeb:io'))

nodeb/templates/nodeb/about.html
{% extends "nodeb/base.html" %}

{% load static %}

{% block additional_headers %}
<link rel="stylesheet" type="text/css" href="{% static 'nodeb/css/style.css' %}" />

<script type="text/javascript">
    //global variable to be used from newsite.js script
    var NewSitePlan = {
        'ajax_url': "{% url 'nodeb:nodebajax' %}",
        'static_url': '{% static "nodeb/" %}'
    };
</script>

{% endblock %}


{% block navigation %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'nodeb:nodeb-plan' %}">Home</a></li>
        <li><a href="{% url 'nodeb:search' %}">Search</a></li>
        <li class="active"><a href="#">About</a></li>
        <li><a href="{% url 'nodeb:io' %}">Import/Export</a></li>
        <li><a href="#">Rehome</a></li>
    </ul>
{% endblock %}

{% block container %}
    <div class="page-header">
        <h3>Statistical analysis</h3>
    </div>

    <ul class="nav nav-tabs secondary_navigation">
        <li tab="ucell_data" class="active" ><a href="#">Ucell</a></li>
        <li tab="spu_data" ><a href="#">SPU Information</a></li>
        <li tab="recently_planned" ><a href="#">Recent Plans</a></li>
    </ul>

    <div id="ucell_data" class="well well-lg nav_details">
        <ul>
            <li> Database Last Updated: {{ context.ucell.last_updated }} by {{ context.ucell.updated_by }}</li>
            <li> RNC No: {{ context.ucell.rnc_count }}  </li>
            <li> Nodeb No: {{ context.ucell.site_count }} </li>
        </ul>
    </div>

    <div id="spu_data" class="well well-lg display_none nav_details">
        <ul>
            <li> Database Last Updated: {{ context.spu.last_updated }} by {{ context.spu.updated_by }} </li>
            <li> HW RNC Count: {{ context.spu.rnc_count }} </li>
        </ul>
    </div>

    <div id="recently_planned" class="well well-lg display_none nav_details">

        <table class="table">
            <thead>
                <tr>
                    <th>Site</th><th>Lat, Lon</th><th>RNC</th><th>LAC</th><th>RAC</th><th>URA</th>
                    <th>RNC IP</th><th>Plan Date</th><th>Plan by</th>
                </tr>
            </thead>
            <tbody id="recently_planned_body"> </tbody>
        </table>
    </div>


{% endblock %}

{% block additional_footer %}
    <!-- javascript -->
    <script src="{% static 'nodeb/js/about.js' %}"></script>
{% endblock %}

nodeb/templates/nodeb/io.html
{% extends "nodeb/base.html" %}

{% load static %}


{% block additional_headers %}
    <script type="text/javascript">
        //global variable to be used from newsite.js script
        var NodebPlanIO = {
            'ajax_url': '{% url "nodeb:io" %}',
            'static_url': '{% static "nodeb/" %}'
        };
    </script>
{% endblock %}

{% block navigation %}
 <ul class="nav navbar-nav">
    <li><a href="{% url 'nodeb:nodeb-plan' %}">Home</a></li>
    <li><a href="{% url 'nodeb:search' %}">Search</a></li>
    <li><a href="{% url 'nodeb:about' %}">About</a></li>
    <li class="active" ><a href="{% url 'nodeb:io' %}">Import/Export</a></li>
    <li><a href="#">Rehome</a></li>
 </ul>

{% endblock %}

{% block container %}
<div class="page-header">
    <h3>Data Import & Export</h3>
</div>

<div class="well well-lg">
    <h3>Instructions for Import</h3>
    <ul>
        <li>Both xlsx & xls files are supported.</li>
        <li>Every cell might not have any garbage ( e.g #NA ) or empty values.</li>
        <li>Data might be kept in active sheet (sheet1) and also make sure sheet name is sheet1</li>
        <li><strong>Update UCELL: </strong>Existing records will be updated based on provided data and new records will be added.</li>
        <li><strong>New UCELL: </strong>Existing records will be deleted instantly and all records will be added.</li>
        <li><strong>SPU:</strong> Existing records will be updated based on provided data and new records will be added </li>
        <li>Sample Files:
            <a href="{% static 'nodeb/sample/Sample_Ucell.xls' %}">Sample Ucell</a>,
            <a href="{% static 'nodeb/sample/SPU_INFO_UPDATED.xlsx' %}">Sample SPU</a>
        </li>
    </ul>
    <h3>Instructions for Export</h3>
    <ul>
        <li>Please click on the links to download.</li>
        <li>  Downloads:
            <a target="_blank" href="{% url 'nodeb:download' 'spu' %}">SPU</a>,
            <a target="_blank" href="{% url 'nodeb:download' 'latlon' %}">Co-Ordinates</a>,
            <a target="_blank" href="{% url 'nodeb:download' 'ucell' %}">UCELL</a>
        </li>
    </ul>
</div>

<div class="progress" style="display: none;">
  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0"
  aria-valuemin="0" aria-valuemax="100" style="width:30%">
    30%
  </div>
</div>

<div class="alert alert-success fade in display_none">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>Gcell</strong>: <span id="success_message"> </span>
</div>

<p id="ajax_processing_message" class="lead display_none"><code> Please wait until success message  </code></p>

<form id="ioform" action="{% url 'nodeb:io' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <table class="table-sm">
        <tr>
            <td>
                <label for="iofile" class="custom-file">
                    <input id="iofile" class="custom-file-input btn" type="file" name="{{ context.form.file.name }}">
                </label>
            </td>
             <td>
                <label for="id_type"> Type </label>
                    {{ context.form.type }}
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input id="submit_button" style="height: 100%" class="btn btn-primary" type="submit" value="Start Uploading" />
                <img id="upload_progress" class="display_none" alt="ajax_loader" src="{% static 'newsite/images/facebook.gif' %}" />
            </td>
        </tr>
    </table>
</form>

{% endblock %}

{% block additional_footer %}
    <!-- javascript -->
    <script src="{% static 'nodeb/js/io.js' %}"></script>
    <script src="{% static 'nodeb/js/lib/jquery-cookie.js' %}"></script>
    <script src="{% static 'nodeb/js/lib/jquery.form.min.js' %}"></script>
{% endblock %}

nodeb/templates/nodeb/map.html
{% extends "nodeb/base.html" %}

{% load static %}

{% block additional_headers %}

    <link rel="stylesheet" type="text/css" href="{% static 'nodeb/css/style.css' %}" />
    <script type="text/javascript">
        //global variable to be used from newsite.js script
        var NewSitePlan = {
            'ajax_url': "{% url 'nodeb:nodebajax' %}",
            'static_url': '{% static "nodeb/" %}'
        };
    </script>
{% endblock %}

{% block navigation %}

    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="{% url 'nodeb:search' %}">Search</a></li>
        <li><a href="{% url 'nodeb:about' %}">About</a></li>
       <li><a href="{% url 'nodeb:io' %}">Import/Export</a></li>
        <li><a href="#">Rehome</a></li>
    </ul>

{% endblock %}

{% block container %}


    <form action="{% url 'nodeb:nodeb-plan' %}" method="post">
        {% csrf_token %}
        <table class="table table-hover">
            <thead class="thead-inverse">
                <tr>
                    <th>CNP WR</th>
                    <th>IPwave WR</th>
                    <th>Lat</th><th>Lon</th>
                    <th>Site</th>
                    <th>Vendor</th>
                    <th>Nearest Site</th>
                    <th>Planned RNC</th>
                    <th>LAC</th>
                    <th>RAC</th>
                    <th>PLMN</th>
                    <th>URA</th>
                    <th>Distance </th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody table-hover>
                {% for ss in data %}
                <tr id="{{ ss.ipwavewr }}-{{ forloop.counter }}">
                    <td class="cnp_wr"> <input type="hidden" name="{{ form.cnp_wr.name }}" value="{{ ss.cnpwr }}"  >{{ ss.cnpwr }} </td>
                    <td class="ipwave_wr"> <input type="hidden" name="{{ form.ipwave_wr.name }}" value="{{ ss.ipwavewr }}"  > {{ ss.ipwavewr }} </td>
                    <td class="input_lat"> <input type="hidden" name="{{ form.lat.name }}" value="{{ ss.lat }}"> {{ ss.lat }} </td>
                    <td class="input_lon"> <input type="hidden" name="{{ form.lon.name }}" value="{{ ss.lon }}"> {{ ss.lon }} </td>
                    <td class="input_site"> <input type="hidden" name="{{ form.site.name }}" value="{{ ss.site }}" > {{ ss.site }} </td>
                    <td class="input_vendor"> <input type="hidden" name="{{ form.vendor.name }}" value="{{ ss.vendor }}" /> {{ ss.vendor }} </td>
                    <td class="nearest_site"> {{ ss.nearest_site }} </td>
                    <td class="proposed_rnc"> <input type="hidden" name="{{ form.rnc.name }}" value="{{ ss.proposed_rnc }}"  > <span> {{ ss.proposed_rnc }} </span> </td>
                    <td class="proposed_lac"> <input type="hidden" name="{{ form.lac.name }}" value="{{ ss.proposed_lac }}"  > <span> {{ ss.proposed_lac }} </span> </td>
                    <td class="proposed_rac"> <input type="hidden" name="{{ form.rac.name }}" value="{{ ss.proposed_rac }}"  > <span> {{ ss.proposed_rac }} </span> </td>
                    <td class="proposed_plmn"> <input type="hidden" name="{{ form.plmn.name }}" value="{{ ss.proposed_plmn }}"  > <span> {{ ss.proposed_plmn }} </span> </td>
                    <td class="proposed_ura"> <input type="hidden" name="{{ form.ura.name }}" value="{{ ss.proposed_ura }}"  > <span> {{ ss.proposed_ura }} </span> </td>
                    <td class="nearest_site_distance"> {{ ss.distance }} </td>
                    <td> <button name="{{ ss.ipwavewr }}-{{ forloop.counter }}" class="btn btn-default justify-individual-plan">Update </button> <img class="ajax_loader display_none" src="{% static 'nodeb/images/facebook.gif' %}" /> </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="14">
                        <a href="{% url 'nodeb:nodeb-plan' %}"><input type="button" value="Upload another file" class="btn btn-link" /> </a>&nbsp; &nbsp; <input class="btn-primary btn" type="submit" value="Save and Download Plan" />
                    </th>
                </tr>
            </tfoot>
        </table>
    </form>

    <div id="map"></div>
{% endblock %}

{% block additional_footer %}
    <!-- javascript -->
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGiluMgQFfw2abMSw4_KCEqNvxszjoQVk">
    </script>
    <script src="{% static 'nodeb/js/map.js' %}"></script>
{% endblock %}