cnp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from log.forms import LoginForm

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^newsite/', include('newsite.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^nodeb/', include('nodeb.urls')),
    url(r'^process/', include('process.urls')),
    url(r'^igw/', include('igw.urls')),
    url(r'', include('log.urls')),
    url(r'^login/', auth_views.login, name='login', kwargs={'template_name': 'log/login.html', 'authentication_form': LoginForm}),
    url(r'^logout/', auth_views.logout, name='logout', kwargs={'next_page': '/login'} ),
]

report/urls.py
from django.conf.urls import url
from .views import HrTraffic, SummaryTraffic, ImportExport, Traffic, ThroughputVolume, NodeOvershoot, Throughput

app_name = 'report'
urlpatterns = [
    url(r'^hourlytraffic$', HrTraffic.as_view(), name='hourlytraffic'),
    url(r'^$', Traffic.as_view(), name='traffic'),
    url(r'^summarytraffic$', SummaryTraffic.as_view(), name='summarytraffic'),
    url(r'^io$', ImportExport.as_view(), name='io'),
    url(r'^volumetraffic$', ThroughputVolume.as_view(), name='volumetraffic'),
    url(r'^throughput$', Throughput.as_view(), name='throughput'),
    url(r'^overshoot$', NodeOvershoot.as_view(), name='overshoot'),
]

report/models.py
from django.db import models
from django.utils import timezone
from datetime import date, timedelta


#hourly traffic model
class HourlyTraffic( models.Model ):
    datetime =  models.DateTimeField(default=timezone.now, blank=True)
    day = models.DateField(blank=True)
    hour = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    traffic = models.FloatField(default=0)

    def __str__(self):
        return self.datetime.strftime('%Y-%m-%d %H:%M:%S')


#summary traffic model
class SummaryTraffic( models.Model ):
    day = models.DateField(blank=True)
    hlr_subscriber = models.IntegerField(default=0)
    vlr_registered = models.IntegerField(default=0)
    vlr_active = models.IntegerField(default=0)
    bh_traffic_erl = models.FloatField(default=0)
    bh_call_attempt = models.IntegerField(default=0)
    hw_capacity_erl = models.FloatField(default=0)
    sw_capacity_erl = models.FloatField(default=0)
    forecast_erl = models.FloatField(default=0)


#GGSN Volumne traffic
class GiTraffic(models. Model):
    datetime = models.DateTimeField(default=timezone.now, blank=True)
    day = models.DateField(blank=True)
    hour = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    ne_name = models.CharField(max_length=500)
    uwg_function = models.CharField(max_length=500)
    gi_traffic = models.FloatField(default=0)       #TB
    gi_throughput = models.FloatField(default=0)    #MB/s ( megabyte per seconds )
    sgi_traffic = models.FloatField(default=0)      #TB
    sgi_throughput = models.FloatField(default=0)  # MB/s ( megabyte per seconds )

    def __str__(self):
        return self.ne_name


#Overshoot of Core Nodes
class Overshoot(models.Model):
    NODE_TYPE = (('mss', 'MSS'), ('mgw', 'MGW'))
    node_name = models.CharField(max_length=500, unique=True)
    node_type = models.CharField(max_length=500, choices=NODE_TYPE, default='mss')
    overshoot_count = models.IntegerField(default=0)
    day = models.DateField(blank=True)
    def __str__(self):
        return self.node_name


#Meta information and corresponding values
class SiteMeta(models.Model):
    meta_key = models.CharField(max_length=500, default=None, blank=True, null=True)
    meta_value = models.CharField(max_length=500, default=None, blank=True, null=True)
    remarks = models.CharField(max_length=500, default=None, blank=True, null=True)

report/forms.py
from django import forms

#handle data import to database
TYPES = (
    ('summarytraffic', 'Summary Traffic'),
    ('gitraffic', 'Gi Traffic'),
    ('15_min_traffic', '15 Minutes Netwok Traffic'),
)
class DataIO( forms.Form ):
    file = forms.FileField()
    type = forms.ChoiceField(choices=TYPES, required=True)

report/views.py
from django.shortcuts import render
from django.views import View
from .helper import QueryTraffic, SummaryTrafficHelper, TrafficHelper, GGSNThroughputHelper, NodeOvershootHelper
import json, sys
from django.core.serializers.json import DjangoJSONEncoder
from datetime import date, timedelta, datetime
from django.utils import timezone
from .forms import DataIO
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse


# Create your views here.

#Home page of traffic ( ../report/ )
class Traffic( View, QueryTraffic):

    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    def get(self, request):

        if (request.is_ajax()):
            if request.GET.get('type', None) == 'hourly_traffic':
                day = request.GET.get('day', None)
                data = TrafficHelper().get_hourly_traffic(day)
            else:
                pass

            return JsonResponse(data, safe=False)

        # if not ajax then it will proceed
        try:
            day = request.GET.get('day')
            day = day.strip()
            traffic = self.get_hourly_traffic(day)
        except:
            day = ''
            traffic = self.get_hourly_traffic()

        context = {
            'title': 'CNP Report: Hourly Traffic'
        }
        return render(request, 'report/traffic.html', {'context': context})


class HrTraffic( View, QueryTraffic ):

    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    def get(self, request):
        try:
            if request.GET.get('day') is None:
                day = timezone.now() - timedelta(days=1, hours=-6)
                day = day.strftime("%Y-%m-%d")
            else:
                day = request.GET.get('day').strip()

            traffic = self.get_hourly_traffic(day)
            gi_throuput = GGSNThroughputHelper().get_hourly_throughput(day) #2G+3G+4G
            sgi_throughput = GGSNThroughputHelper().get_hourly_sgi_throughput(day) #only 4G
        except:
            print("Unexpected error:", sys.exc_info()[0])
            raise

        context = {
            'title': 'CNP Report: Hourly Traffic',
            'day1': json.dumps(traffic, cls=DjangoJSONEncoder),
            'throughput': json.dumps(gi_throuput, cls=DjangoJSONEncoder),
            'sgi_throughput': json.dumps(sgi_throughput, cls=DjangoJSONEncoder),
            #'recent_days': self.get_recent_days(),
            'selected_day': day
        }
        return render(request, 'report/hourly_traffic.html', {'context': context})

#summary core traffic
class SummaryTraffic( View, SummaryTrafficHelper ):

    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    def get(self, request):
        try:
            startDate = datetime.strptime( request.GET.get('from', ''), '%Y-%m-%d' )
            endDate = datetime.strptime( request.GET.get('to', ''), '%Y-%m-%d')
        except:
            endDate = date.today()
            startDate = endDate - timedelta(30)

        if(request.is_ajax()):
            data = self.get_summary_data(request.GET.get('type', None), startDate, endDate)
            return JsonResponse(data, safe=False)
        else:
            context = {
                'title': 'CNP Report: Summary Traffic',
                'startDate': startDate.strftime('%Y-%m-%d'),
                'endDate': endDate.strftime('%Y-%m-%d'),
            }
            return render( request, 'report/summary_traffic.html', {'context': context} )


#import & export data for rport
class ImportExport( LoginRequiredMixin, View ):
    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    #Inital page to import and export
    def get( self, request ):
        context = {
            'title': 'CNP Report: IO',
            'form': DataIO
        }
        return render( request, 'report/io.html', {'context': context} )


    #This function is called uring ajax requests while uploading raw data
    def post( self, request ):
        form = DataIO( request.POST, request.FILES )
        data = {}
        if form.is_valid():
            if form.cleaned_data['type'] == 'summarytraffic':
                data = SummaryTrafficHelper().save_traffic_data( request.FILES['file'] )
                data['is_valid'] = True
            elif form.cleaned_data['type'] == 'gitraffic':
                data = GGSNThroughputHelper().save_gi_traffic( request.FILES['file'] )
            elif form.cleaned_data['type'] == '15_min_traffic':
                data = TrafficHelper().save_15_mins_traffic( request.FILES['file'] )
            else:
                data['is_valid'] = False
        else:
            data['is_valid'] = False

        return JsonResponse(data)



#GGSN Throughput
class ThroughputVolume( View ):

    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    def get(self, request):
        try:
            startDate = datetime.strptime(request.GET.get('from', ''), '%Y-%m-%d')
            endDate = datetime.strptime(request.GET.get('to', ''), '%Y-%m-%d')
        except:
            endDate = date.today() - timedelta(1)
            startDate = endDate - timedelta(30)

        if request.is_ajax():
            type = request.GET.get('type', None)
            if type == 'calling_minutes':
                data = TrafficHelper().get_calling_minutes(type, startDate, endDate)
            else:
                data = GGSNThroughputHelper().get_data_volume(type, startDate, endDate)  # 2G+3G, 4G or both have been segregated throgh type name

            data['startDate'] = startDate.strftime('%Y-%m-%d')
            data['endDate'] = endDate.strftime('%Y-%m-%d')
            return JsonResponse(data, safe=False)


        context = {
            'title': 'CNP Report: Data Volume & Calling Minutes',
            'startDate': startDate.strftime('%Y-%m-%d'),
            'endDate': endDate.strftime('%Y-%m-%d')
        }
        return render(request, 'report/volume_traffic.html', {'context': context})



#Overshoot calculations
class NodeOvershoot( View ):

    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    def get(self, request):

        if (request.is_ajax()):
            data = NodeOvershootHelper().get_overshoots(request.GET.get('type', None))
            return JsonResponse(data, safe=False)

        context = {
            'title': 'CNP Report: Overshoots of Core Nodes'
        }
        return render(request, 'report/overshoot.html', {'context': context})


#throughput
class Throughput( View ):

    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    def get(self, request):
        try:
            startDate = datetime.strptime(request.GET.get('from', ''), '%Y-%m-%d')
            endDate = datetime.strptime(request.GET.get('to', ''), '%Y-%m-%d')
        except:
            endDate = date.today() - timedelta(1)
            startDate = endDate - timedelta(30)

        if request.is_ajax():
            type = request.GET.get('type', None)
            if type == 'gi_throughput':
                data = GGSNThroughputHelper().get_daily_peak_throughput(startDate, endDate) #2G+3G+4G
            elif type == 'sgi_throughput':
                data = GGSNThroughputHelper().get_daiy_peak_sgi_throughput(startDate, endDate) #only 4G
            else:
                data = TrafficHelper().get_daily_traffic(startDate, endDate)

            data['startDate'] = startDate.strftime('%Y-%m-%d')
            data['endDate'] = endDate.strftime('%Y-%m-%d')
            return JsonResponse(data, safe=False)

        context = {
            'title': 'CNP Report: Daily Traffic and Throughput pattern',
            'startDate': startDate.strftime('%Y-%m-%d'),
            'endDate': endDate.strftime('%Y-%m-%d')
        }
        return render(request, 'report/throughput.html', {'context': context})

report/templates/report/hourly_traffic.html
{% extends "report/base.html" %}

{% load static %}

{% block additional_headers %}
    <script src="{% static 'report/js/jquery3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'report/highchart/highchart5.0.10.js' %}"></script>
    <!-- bootstrap date picker csss -->
    <link rel="stylesheet" href="{% static 'report/bootstrap-datepicker3/bootstrap-datepicker3.css' %}"/>

    <style type="text/css">
        div.map_container{
            padding: 5px;
            background-color: rgba(63, 74, 84, 0.13);
        }
    </style>

<script type="text/javascript">

    var Report = {
        'hourlytraffic': '{% url "report:hourlytraffic" %}'
    };

    function pyjson_to_jsjson( pyjson ){
        var myDjangoList = ((pyjson).replace(/&(l|g|quo)t;/g, function(a,b){
            return {
                l   : '<',
                g   : '>',
                quo : '"'
            }[b];
        }));

        myDjangoList = myDjangoList.replace(/u'/g, '\'');
        myDjangoList = myDjangoList.replace(/'/g, '\"');
        return myDjangoList;
    }

    function draw_map(data){
        //dataDay1 = pyjson_to_jsjson("{{ context.day1 }}");
        //dataDay1 = $.parseJSON(dataDay1);

        Highcharts.chart(data.container, {
            chart: {
                type: 'line'
            },
            credits: {
                enabled: false,
            },
            title: {
                text: data.title
            },
            subtitle: {
                text: data.subtitle
            },
            xAxis: {
                title:{
                    text: data.x
                },
                categories: data.categories
            },
            yAxis: {
                title: {
                    text: data.y
                },
                max: data.y_max
            },
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true,
                        allowOverlap: true,
                        rotation: -90,
                        format: data.format,
                        y: -30
                    },
                    enableMouseTracking: true,

                }
            },
            series: [{
                showInLegend: false,
                name: data.series.name,
                data: data.series.data,
                tooltip: {
                    valueSuffix: ' ' + data.series.tooltip
                }
            }],
             exporting: {
                enabled: true
            }
        });
    }

    jQuery(document).ready(function ($) {
        cs_data = pyjson_to_jsjson("{{ context.day1 }}");
        ps_data = pyjson_to_jsjson("{{ context.throughput }}");
        lte_data = pyjson_to_jsjson("{{ context.sgi_throughput }}")
        ps_data = $.parseJSON(ps_data);
        cs_data = $.parseJSON(cs_data);
        lte_data = $.parseJSON(lte_data);

        maps = [
            {
                'title': 'Hourly Network Traffic',
                'subtitle': "Date: " + cs_data.day,
                'container': 'container1',
                'x': 'Hour',
                'y': 'Traffic ( kErl )',
                'y_max': 2600,
                'categories': cs_data.hour,
                'format': '{point.y:.1f}',
                'series': {
                    'name': cs_data.day,
                    'data': cs_data.traffic,
                    'tooltip': 'kErl'
                }
            },
            {
                'title': 'Hourly Network Throughput',
                'subtitle': "Date: " + ps_data.day,
                'container': 'container2',
                'x': 'Hour',
                'y': 'Througput ( Gbps )',
                'y_max': 300,
                'categories': ps_data.hour,
                'format': '{point.y:.2f}',
                'series': {
                    'name': ps_data.day,
                    'data': ps_data.throughput,
                    'tooltip': 'Gbps'
                }
            },
            {
                'title': 'Hourly LTE Throughput',
                'subtitle': "Date: " + lte_data.day,
                'container': 'container3',
                'x': 'Hour',
                'y': 'Througput ( Gbps )',
                'y_max': 50,
                'categories': lte_data.hour,
                'format': '{point.y:.2f}',
                'series': {
                    'name': lte_data.day,
                    'data': lte_data.throughput,
                    'tooltip': 'Gbps'
                }
            }

        ];

         $.each(maps, function (i, map) {
             draw_map(map);
         });

    })
</script>

{% endblock %}

{% block navigation %}
    <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'report:hourlytraffic' %}">Hourly Traffic</a></li>
        <li><a href="{% url 'report:summarytraffic' %}">Summary Traffic</a></li>
        <li><a href="{% url 'report:volumetraffic' %}">Volume Traffic</a></li>
        <li><a href="{% url 'report:throughput' %}">Daily Traffic</a></li>
        <li><a href="{% url 'report:overshoot' %}">Overshoot</a></li>
        <li><a href="{% url 'report:io' %}">Import/Export</a></li>
    </ul>
{% endblock %}

{% block container %}


    <div class="well search-box" style="text-align: right">
        <label for="start_date" style="text-align: left">
            <input value="{{ context.selected_day }}"  id="start_date" class="span2 col-md form-control" name="startDate" placeholder=" YYYY-MM-DD " type="text">
        </label> &nbsp;&nbsp;

        <label for="generate_report">
            <input id="generate_report" type="button" class="btn btn-primary span2 col-md form-control" value="Generate Report">
        </label>
    </div>

    <div class="map_container" id="container1" style="width:100%; height:400px;"></div>
    <div class="map_container" id="container2" style="width:100%; height:400px;"></div>
    <div class="map_container" id="container3" style="width:100%; height:400px;"></div>

    <div>&nbsp;</div>
{% endblock %}

{% block additional_footer %}


    <script type="text/javascript" src="{% static 'report/js/hourly_traffic.js' %}" > </script>
    <!-- bootstrap date picker javascript -->
    <script type="text/javascript" src="{% static 'report/bootstrap-datepicker3/bootstrap-datepicker.min.js' %}" > </script>
{% endblock %}

report/templates/report/io.html
{% extends "report/base.html" %}

{% load static %}

{% block additional_headers %}
    <script type="text/javascript">
        //global variable to be used from newsite.js script
        var ReportIO = {
            'ajax_url': '{% url "report:io" %}',
            'static_url': '{% static "report/" %}'
        };
    </script>
{% endblock %}


{% block navigation %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'report:hourlytraffic' %}">Hourly Traffic</a></li>
        <li><a href="{% url 'report:summarytraffic' %}">Summary Traffic</a></li>
        <li><a href="{% url 'report:volumetraffic' %}">Volume Traffic</a></li>
        <li><a href="{% url 'report:throughput' %}">Daily Traffic</a></li>
        <li><a href="{% url 'report:overshoot' %}">Overshoot</a></li>
        <li class="active"><a href="{% url 'report:io' %}">Import/Export</a></li>
    </ul>
{% endblock %}

{% block container %}
    <div class="page-header">
        <h3>Data Import & Export</h3>
    </div>

    <div class="well well-lg">
        <h3>Instructions</h3>
        <ul>
            <li>Both xlsx & xls files are supported.</li>
            <li>Every cell might not have any garbage ( e.g #NA ) or empty values.</li>
            <li>Sample Files:
                <a href="{% static 'report/sample/MSS_data.xlsx' %}">Summary Traffic</a>,
                <a href="{% static 'report/sample/GGSN_volume_throughput.xlsx' %}">GGSN Volume & Throughput</a>,
                <a href="{% static 'report/sample/15_mins_data.xlsx' %}"> 15 Minutes Traffic </a>
            </li>
            <li>Existing record will be updated immediately & it cannot be revoked</li>
        </ul>
    </div>

    <div class="progress" style="display: none;">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0"
      aria-valuemin="0" aria-valuemax="100" style="width:30%">
        30%
      </div>
    </div>

    <div class="alert alert-success fade in display_none">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong> Summary Traffic </strong>: <span id="success_message"> </span>
    </div>

    <p id="ajax_processing_message" class="lead display_none"><code> Please wait until success message  </code></p>

    <form id="ioform" action="{% url 'report:io' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <table class="table-sm">
            <tr>
                <td>
                    <label for="iofile" class="custom-file">
                        <input id="iofile" class="custom-file-input btn" type="file" name="{{ context.form.file.name }}">
                    </label>
                </td>
                 <td>
                    <label for="id_type"> Type </label>
                        {{ context.form.type }}
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input id="submit_button" style="height: 100%" class="btn btn-primary" type="submit" value="Start Uploading" />
                    <img id="upload_progress" class="display_none" alt="ajax_loader" src="{% static 'report/images/facebook.gif' %}" />
                </td>
            </tr>
        </table>
    </form>

{% endblock %}

{% block additional_footer %}
    <!-- javascript -->
    <script src="{% static 'report/js/jquery3.1.1.min.js' %}"></script>
    <script src="{% static 'report/js/io.js' %}"></script>
    <script src="{% static 'report/js/lib/jquery-cookie.js' %}"></script>
    <script src="{% static 'report/js/lib/jquery.form.min.js' %}"></script>
{% endblock %}

report/templates/report/overshoot.html
{% extends "report/base.html" %}

{% load static %}

{% block additional_headers %}
    <script type="text/javascript">
        var Report = {
            'hourlytraffic': '{% url "report:hourlytraffic" %}',
            'traffic': '{% url "report:traffic" %}',
            'volumetraffic': '{% url "report:volumetraffic" %}',
            'overshoot': '{% url "report:overshoot" %}'
        };
    </script>

    <style type="text/css">
        div.map_container{
            padding: 5px;
            background-color: rgba(63, 74, 84, 0.13);
        }
    </style>

{% endblock %}

{% block navigation %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'report:hourlytraffic' %}">Hourly Traffic</a></li>
        <li><a href="{% url 'report:summarytraffic' %}">Summary Traffic</a></li>
        <li><a href="{% url 'report:volumetraffic' %}">Volume Traffic</a></li>
        <li><a href="{% url 'report:throughput' %}">Daily Traffic</a></li>
        <li class="active"><a href="{% url 'report:overshoot' %}">Overshoot</a></li>
        <li><a href="{% url 'report:io' %}">Import/Export</a></li>
    </ul>
{% endblock %}

{% block container %}
    <div  class="map_container" id="container_1" style="width:100%; height: 500px;"></div>
    <div  class="map_container" id="container_2" style="width:100%; height: 1300px"></div>

{% endblock %}

{% block additional_footer %}

    <script type="text/javascript" src="{% static 'report/highchart/highchart5.0.10.js' %}"></script>
    <script type="application/javascript" src="{% static 'report/highchart/moduleexporting5.0.11.js' %}"></script>
    <script type="text/javascript" src="{% static 'report/js/overshoot.js' %}" > </script>

{% endblock %}

report/templates/report/throughput.html
{% extends "report/base.html" %}

{% load static %}

{% block additional_headers %}
    <link rel="stylesheet" href="{% static 'report/bootstrap-datepicker3/bootstrap-datepicker3.css' %}"/>
    <script type="text/javascript">
        var Report = {
            'hourlytraffic': '{% url "report:hourlytraffic" %}',
            'traffic': '{% url "report:traffic" %}',
            'throughput': '{% url "report:throughput" %}'
        };
    </script>

    <style type="text/css">
        div.map_container{
            padding: 5px;
            background-color: rgba(63, 74, 84, 0.13);
        }
    </style>

{% endblock %}

{% block navigation %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'report:hourlytraffic' %}">Hourly Traffic</a></li>
        <li><a href="{% url 'report:summarytraffic' %}">Summary Traffic</a></li>
        <li><a href="{% url 'report:volumetraffic' %}">Volume Traffic</a></li>
        <li class="active"><a href="{% url 'report:throughput' %}">Daily Traffic</a></li>
        <li><a href="{% url 'report:overshoot' %}">Overshoot</a></li>
        <li><a href="{% url 'report:io' %}">Import/Export</a></li>
    </ul>
{% endblock %}

{% block container %}

    <div class="well search-box" style="text-align: right">
        <label for="start_date" style="text-align: left">
            Start date <input value="{{ context.startDate }}"  id="start_date" class="span2 col-md form-control" name="startDate" placeholder=" YYYY-MM-DD " type="text">
        </label> &nbsp;&nbsp;
        <label for="end_date" style="text-align: left">
            End date <input value="{{ context.endDate }}" id="end_date" class="span2 col-md form-control" name="endDate" placeholder=" YYYY-MM-DD " type="text">
        </label>&nbsp;&nbsp;
        <label for="generate_report">
            &nbsp;<input id="generate_report" type="button" class="btn btn-primary span2 col-md form-control" value="Generate Report">
        </label>
    </div>

    <div  class="map_container" id="container_1" style="width:100%; height:400px;"></div>
    <div  class="map_container" id="container_2" style="width:100%; height:400px;"></div>
    <div  class="map_container" id="container_3" style="width:100%; height:400px;"></div>
    <div>&nbsp;</div>

{% endblock %}


{% block additional_footer %}

    <script type="text/javascript" src="{% static 'report/highchart/highchart5.0.10.js' %}"></script>
    <script type="application/javascript" src="{% static 'report/highchart/moduleexporting5.0.11.js' %}"></script>
    <!-- bootstrap date picker javascript -->
    <script type="text/javascript" src="{% static 'report/bootstrap-datepicker3/bootstrap-datepicker.min.js' %}" > </script>
    <script type="text/javascript" src="{% static 'report/js/throughput.js' %}" > </script>

{% endblock %}

report/templates/report/volume_traffic.html
{% extends "report/base.html" %}

{% load static %}

{% block additional_headers %}
    <link rel="stylesheet" href="{% static 'report/bootstrap-datepicker3/bootstrap-datepicker3.css' %}"/>
    <script type="text/javascript">
        var Report = {
            'hourlytraffic': '{% url "report:hourlytraffic" %}',
            'traffic': '{% url "report:traffic" %}',
            'volumetraffic': '{% url "report:volumetraffic" %}'
        };
    </script>

    <style type="text/css">
        div.map_container{
            padding: 5px;
            background-color: rgba(63, 74, 84, 0.13);
        }
    </style>

{% endblock %}

{% block navigation %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'report:hourlytraffic' %}">Hourly Traffic</a></li>
        <li><a href="{% url 'report:summarytraffic' %}">Summary Traffic</a></li>
        <li class="active"><a href="{% url 'report:volumetraffic' %}">Volume Traffic</a></li>
        <li><a href="{% url 'report:throughput' %}">Daily Traffic</a></li>
        <li><a href="{% url 'report:overshoot' %}">Overshoot</a></li>
        <li><a href="{% url 'report:io' %}">Import/Export</a></li>
    </ul>
{% endblock %}

{% block container %}

    <div class="well search-box" style="text-align: right">
        <label for="start_date" style="text-align: left">
            Start date <input value="{{ context.startDate }}"  id="start_date" class="span2 col-md form-control" name="startDate" placeholder=" YYYY-MM-DD " type="text">
        </label> &nbsp;&nbsp;
        <label for="end_date" style="text-align: left">
            End date <input value="{{ context.endDate }}" id="end_date" class="span2 col-md form-control" name="endDate" placeholder=" YYYY-MM-DD " type="text">
        </label>&nbsp;&nbsp;
        <label for="generate_report">
            &nbsp;<input id="generate_report" type="button" class="btn btn-primary span2 col-md form-control" value="Generate Report">
        </label>
    </div>

    <div  class="map_container" id="container_1" style="width:100%; height:400px;"></div>
    <div  class="map_container" id="container_2" style="width:100%; height:400px;"></div>
    <div  class="map_container" id="container_3" style="width:100%; height:400px;"></div>
    <div  class="map_container" id="container_4" style="width:100%; height:400px;"></div>
    <div>&nbsp;</div>

{% endblock %}


{% block additional_footer %}

    <script type="text/javascript" src="{% static 'report/highchart/highchart5.0.10.js' %}"></script>
    <script type="application/javascript" src="{% static 'report/highchart/moduleexporting5.0.11.js' %}"></script>
    <!-- bootstrap date picker javascript -->
    <script type="text/javascript" src="{% static 'report/bootstrap-datepicker3/bootstrap-datepicker.min.js' %}" > </script>
    <script type="text/javascript" src="{% static 'report/js/volume_traffic.js' %}" > </script>

{% endblock %}