cnp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from log.forms import LoginForm

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^newsite/', include('newsite.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^nodeb/', include('nodeb.urls')),
    url(r'^process/', include('process.urls')),
    url(r'^igw/', include('igw.urls')),
    url(r'', include('log.urls')),
    url(r'^login/', auth_views.login, name='login', kwargs={'template_name': 'log/login.html', 'authentication_form': LoginForm}),
    url(r'^logout/', auth_views.logout, name='logout', kwargs={'next_page': '/login'} ),
]

newsite/urls.py
from django.conf.urls import url
from .views import NearestSites, NewSitePlan, About, ImportExport, Search, Dashboard, Rehome, Download

app_name = 'newsite'
urlpatterns = [
    url(r'^$', NewSitePlan.as_view(), name='new-site-plan'),
    url(r'^nearestsite/$', NearestSites.as_view(), name='nearest-sites'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^io/$', ImportExport.as_view(), name='io'),
    url(r'^search/$', Search.as_view(), name='search'),
    url(r'^dashboard/$', Dashboard.as_view(), name='dashboard'),
    url(r'^rehome/$', Rehome.as_view(), name='rehome'),
    url(r'^download/(?P<type>[a-z]+)/$', Download.as_view(), name='download')
]

newsite/models.py
from django.db import models
from datetime import date

#gcell info which is used for new site plan
class Gcell(models.Model):
    bsc_site = models.CharField(max_length=500, default=None, null=True, blank=True)
    dist = models.CharField(max_length=500, default=None, null=True, blank=True)
    sitename = models.CharField(max_length=500)
    cellname = models.CharField(max_length=500)
    ci = models.IntegerField(default=0)
    bscname = models.CharField(max_length=500)
    lac = models.IntegerField(default=0)
    activestatus = models.CharField(max_length=500, default=None, null=True, blank=True)
    #territory_id = models.IntegerField(default=None, null=True, blank=True)
    #territory = models.CharField(max_length=200, default=None, null=True, blank=True)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    trx = models.IntegerField(default=0, null=True, blank=True)
    traffic = models.FloatField(default=0, null=True, blank=True)

    def __str__(self):
        return self.cellname


#bsc database to keep ip address based on FG2C cards for huawei
class BscDatabase(models.Model):
    bscname = models.CharField(max_length=500)
    vendor = models.CharField(max_length=500, default=None, null=True, blank=True)
    subrack_slot = models.CharField(max_length=500)
    main_address = models.GenericIPAddressField(protocol='both', unpack_ipv4=True)
    gateway_address = models.GenericIPAddressField(protocol='both', unpack_ipv4=True)
    subnet_mask = models.GenericIPAddressField(protocol='both', unpack_ipv4=True)
    network_address = models.GenericIPAddressField(protocol='both', unpack_ipv4=True)

    def __str__(self):
        return self.bscname


#Ericsson database
class EricssonBscDatabase(models.Model):
    bscname = models.CharField(max_length=500)
    vendor = models.CharField(max_length=500, default=None, null=True, blank=True)
    subrack_slot = models.CharField(max_length=500, default=None, null=True, blank=True)
    main_address = models.CharField(max_length=500, default=None)
    gateway_address = models.CharField(max_length=500, default=None)
    subnet_mask = models.CharField(max_length=500, default=None)
    network_address = models.CharField(max_length=500, default=None)

    def __str__(self):
        return self.bscname


#HW Aoip Database
class BscSiteDatabase(models.Model):
    bscname = models.CharField(max_length=500)
    bts = models.CharField(max_length=500, default='NA')
    btscomtype = models.CharField(max_length=500, default='PORTIP')
    btsip = models.GenericIPAddressField(protocol='both', unpack_ipv4=True)
    bscip = models.GenericIPAddressField(protocol='both', unpack_ipv4=True)

    def __str__(self):
        return self.bscname


#aoip database
class AoipDatabase(models.Model):
    sitename = models.CharField(max_length=500)
    bscname = models.CharField(max_length=500)
    lac = models.IntegerField(default=0000)
    subrack_slot = models.CharField(max_length=500)
    bsc_ip = models.CharField(max_length=500)
    bsc_mask = models.CharField(max_length=500)
    bsc_gateway = models.CharField(max_length=500)
    cnp_wr = models.CharField(max_length=500, default=None, null=True, blank=True)
    cnp_wr_no = models.BigIntegerField(default=None, null=True, blank=True)
    ipwave_wr = models.CharField(default='NA', max_length=500)
    username = models.CharField(default='NA', max_length=500)
    plan_date = models.DateField(default=date.today)
    remark = models.TextField(default=None, null=True, blank=True)

    def __str__(self):
        return self.sitename


#site settings
class SiteMeta(models.Model):
    meta_key = models.CharField(max_length=500, default=None, blank=True, null=True)
    meta_value = models.CharField(max_length=500, default=None, blank=True, null=True)
    remarks = models.CharField(max_length=500, default=None, blank=True, null=True)


#Latlong database
class Coordinates(models.Model):
    sitename = models.CharField(max_length=500, default=None, blank=True, null=True)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)

    def __str__(self):
        return self.sitename

newsite/forms.py
from django import forms

#handle first page excel file upload
class UploadFileForm(forms.Form):
    file = forms.FileField()
    plan_uploaded = forms.CharField(widget=forms.HiddenInput())


#Handle final plan download
class FinalPlanDonwload(forms.Form):
    cnp_wr = forms.CharField(widget=forms.HiddenInput())
    ipwave_wr = forms.CharField(widget=forms.HiddenInput())
    site = forms.CharField(widget=forms.HiddenInput())
    bsc = forms.CharField(widget=forms.HiddenInput())
    lac = forms.CharField(widget=forms.HiddenInput())
    lat = forms.CharField(widget=forms.HiddenInput())
    lon = forms.CharField(widget=forms.HiddenInput())


#hanling import and export
TYPES = (
    ('gcell', 'Gcell'),
    ('btsipdata', 'BTS IP Data'),
)
class DataIO(forms.Form):
    file = forms.FileField()
    type = forms.ChoiceField(choices=TYPES, required=True)



#Search fileds in search page
class SearchSites(forms.Form):
    s = forms.CharField()


#Rehoming form
class Rehoming(forms.Form):
    from_bsc = forms.CharField()
    to_bsc = forms.CharField()

newsite/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.views import View
import django_excel as excel
from .forms import UploadFileForm, FinalPlanDonwload, DataIO, SearchSites, Rehoming
from django.contrib.auth.mixins import LoginRequiredMixin
from .helper import NewSitePlanHelper, NearestSitesHelper, AboutHelper, SearchHelper, ImportExportHelper, DownloadHelper


#index page
class NewSitePlan(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    def get(self, request):
        form = UploadFileForm(initial={'plan_uploaded':'Y'})
        context = {'title': 'CNP Plan: 2G Site'}
        return render(request, 'newsite/index.html', {'form': form, 'context': context})

    def post(self, request):
        self.request = request
        context = {'title': 'CNP Plan: 2G Site'}
        if request.POST.get('plan_uploaded') == 'Y' and request.FILES['file']:
            form = UploadFileForm(request.POST, request.FILES)
            planed_form = FinalPlanDonwload

            if form.is_valid():
                data = NewSitePlanHelper().process_latlongfile( request.FILES['file'] )
                return render(request, 'newsite/map.html', {'data': data, 'form': planed_form, 'context': context})

            else:
                form = UploadFileForm
                return render(request, 'newsite/index.html', {'form': form, 'context': context})

        else:
            form = FinalPlanDonwload(request.POST)
            if form.is_valid():
                header = ['WRNO', 'Site Name', 'Target NE(BSC/RNC Name)', 'Subrack,Slot', 'RNC/BSC FG2C (Main) IP Address', 'Subnet mask RNC', 'BSC/RNC Gateway', 'LAC']
                d = [header]
                sites = request.POST.getlist('site')
                proposed_bscs = request.POST.getlist('bsc')
                proposed_lacs = request.POST.getlist('lac')
                ipwave_wrs = request.POST.getlist('ipwave_wr')
                cnp_wrs = request.POST.getlist('cnp_wr')
                lats = request.POST.getlist('lat')
                lons = request.POST.getlist('lon')

                for i in range(len(sites)):
                    bss_info = NewSitePlanHelper().get_bsc_subrack_and_ip(proposed_bscs[i])
                    if len(bss_info) > 0:
                        d.append([ipwave_wrs[i], sites[i], bss_info[0], bss_info[1], bss_info[2], bss_info[4], bss_info[3], proposed_lacs[i]])
                        NewSitePlanHelper().save_log(sites[i], bss_info, ipwave_wrs[i], cnp_wrs[i], proposed_lacs[i], self.request.user.username)  # saving log to database
                        NewSitePlanHelper().save_coordinates(sites[i], lats[i], lons[i])  # saving co-ordinates

                year = "{:%y}".format(timezone.now())
                attachment_name = "WORK_REQUEST_NO_new_site_{}-{}-AbisOIP.xls".format(cnp_wrs[0], year)
                return excel.make_response_from_array(d, 'xls', file_name=attachment_name)
            else:
                return HttpResponse(form.errors)


# ajax handling
class NearestSites(View):
    def get(self, request):
        self.request = request
        if request.GET.get('hook') == 'nearestsites':
            limit = 100
            lat = request.GET.get('lat', None)
            lon = request.GET.get('lon', None)
            site = request.GET.get('site', None)
            data = NearestSitesHelper().get_nearest_sites( lat, lon, site, limit);

        elif request.GET.get('hook') == 'get_bsc_info':
            data = NearestSitesHelper().get_bsc_info( request.GET.get('bscname', None) )

        else:
            data = []
        return JsonResponse(data, safe=False)  # default function to handle json form django 1.8



# about page
class About(View):
    def get(self, request):
        context = {
            'title': 'CNP Plan: about',
            'bts_ip_data': AboutHelper().get_btsip_info(),
            'gcell': AboutHelper().get_gcell_info() ,
            'recently_panned': AboutHelper().get_recent_plans(100)
        }
        return render(request, 'newsite/about.html', {'context': context})


# data import/export
class ImportExport(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'
    permission_denied_message = 'You are not authorized..'

    def get(self, request):
        form = DataIO
        context = {'title': 'CNP Plan: IO', 'form': form }
        return render(request, 'newsite/io.html', {'context': context})

    def post(self, request):
        form = DataIO(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['type'] == 'gcell':
                data = ImportExportHelper().save_gcell( request.FILES['file'] )
            else:
                data = ImportExportHelper().save_btsip( request.FILES['file'] )
        else:
            data = {
                'is_valid': False
            }

        response = JsonResponse(data)
        #response.set_cookie(key='row_count', value=success, path='/')
        return response


#Handling Search functionality at search page
class Search(View):
    def get(self, request):
        if request.is_ajax():
            data = []
            if request.GET.get('hook', None) == 'search':
                form = SearchSites(request.GET)
                if form.is_valid():
                    limit = 350
                    data = SearchHelper().get_nearest_sites( form.cleaned_data['s'].strip(), limit )
                    return JsonResponse(data, safe=False)
            else:
                bsc = request.GET.get('bscname')
                data = SearchHelper().get_bsc_info( request.GET.get('bscname') )

            return JsonResponse(data, safe=False)

        else:
            form = SearchSites
            context = { 'title': 'CNP Plan: Search', 'form': form }
            return render(request, 'newsite/search.html', {'context': context})


#dashboard view
class Dashboard(View):
    def get(self, request):
        context = {'title': 'CNP Plan: Dashboard'}
        return render(request, 'newsite/dashboard.html', {'context': context})


class Rehome(View):
    def get(self, request):
        form = Rehoming
        context = {'title': 'CNP Plan: Rehome', 'form': form}
        return render(request, 'newsite/rehome.html', {'context': context})

    def post(self, request):
        pass


#class Download
class Download(View):
    def get(self, request, type=None):
        download_date = "{:%Y-%m-%d}".format(timezone.now())
        if type == 'latlon':
            data = DownloadHelper().get_whole_latlon()
            return excel.make_response_from_array(data, 'xlsx', file_name='LatLon_DB_' + download_date)
        elif type == 'gcell':
            data = DownloadHelper().get_whole_gcell()
            return excel.make_response_from_array(data, 'xlsx', file_name='GCELL_' + download_date)
        else:
            return HttpResponseRedirect(reverse('newsite:io'))

newsite/templates/newsite/dashboard.html
{% extends "newsite/base.html" %}

{% block navigation %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'newsite:new-site-plan' %}">Home</a></li>
        <li  class="active"><a href="#">Search</a></li>
        <li><a href="{% url 'newsite:about' %}">About</a></li>
        <li><a href="{% url 'newsite:io' %}">Import/Export</a></li>
    </ul>
{% endblock %}

{% block container %}
    <div class="page-header">
        <h3>2G Plan: Search</h3>
    </div>
{% endblock %}

newsite/templates/newsite/index.html
{% extends "newsite/base.html" %}

{% load static %}

{% block navigation %}
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="{% url 'newsite:search' %}">Search</a></li>
        <li><a href="{% url 'newsite:about' %}">About</a></li>
        <li><a href="{% url 'newsite:io' %}">Import/Export</a></li>
        <li><a href="{% url 'newsite:rehome' %}">Rehome</a></li>
    </ul>
{% endblock %}

{% block container %}
    <div class="page-header">
        <h3>Welcome to new site planning</h3>
    </div>

    <div class="well well-lg">
        <h3>Instructions</h3>
        <ul>
            <li>Both xlsx & xls files are supported.</li>
            <li>Every cell might not have any garbage ( e.g #NA ) or empty values.</li>
            <li>Latitude, Longitude might have numerical values.</li>
            <li>PICO BTS: Automatically selects sites of Huawei BSC.</li>
            <li>Sample Files:
                <a href="{% static 'newsite/sample/Sample_Plan.xlsx' %}">Sample Plan</a>
            </li>
        </ul>
    </div>

    <p class="lead"><code> Upload Co-ordinate file and start your plan..  </code></p>

    <form action="{% url 'newsite:new-site-plan' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <table class="table-sm">
            <tr>
                <td>
                    <label class="custom-file">
                    <input class="custom-file-input btn" type="file" name="{{ form.file.name }}" ><span class="custom-file-control"></span>
                    </label>
                </td>
                <td>
                    &nbsp; &nbsp;
                </td>
                <td>
                    <input style="height: 100%" class="btn btn-primary" type="submit" value="Start Planning" />
                </td>
            </tr>
        </table>
        {{ form.plan_uploaded }}
    </form>
{% endblock %}

newsite/templates/newsite/io.html
{% extends "newsite/base.html" %}

{% load static %}


{% block additional_headers %}

    <link rel="stylesheet" type="text/css" href="{% static 'newsite/css/style.css' %}" />
    <script type="text/javascript">
        //global variable to be used from newsite.js script
        var NewSitePlanIO = {
            'ajax_url': '{% url "newsite:io" %}',
            'static_url': '{% static "newsite/" %}'
        };
    </script>
{% endblock %}

{% block navigation %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'newsite:new-site-plan' %}">Home</a></li>
        <li><a href="{% url 'newsite:search' %}">Search</a></li>
        <li><a href="{% url 'newsite:about' %}">About</a></li>
        <li class="active"><a href="#">Import/Export</a></li>
        <li><a href="{% url 'newsite:rehome' %}">Rehome</a></li>
    </ul>
{% endblock %}

{% block container %}
<div class="page-header">
    <h3>Data Import & Export</h3>
</div>

<div class="well well-lg">
    <h3>Instructions for Import</h3>
    <ul>
        <li>Both xlsx & xls files are supported.</li>
        <li>Every cell might not have any garbage ( e.g #NA ) or empty values.</li>
        <li>Latitude, Longitude, TRX, Traffic columns of <strong>Gcell</strong> might have numeric values.</li>
        <li>BTS IP & BSC IP column of <strong>BTS IP Data</strong> might have Generic IPV4 address.</li>
        <li>Sample Files:
            <a href="{% static 'newsite/sample/Sample_Gcell.xlsx' %}">Sample Gcell</a> &
            <a href="{% static 'newsite/sample/Sample_IPPLAN.xlsx' %}">Sample IP Plan</a>
        </li>
        <li>Existing records will be deleted instantly before uploading</li>
    </ul>
    <h3>Instructions for Export</h3>
    <ul>
        <li>Please click on the links to download.</li>
        <li>  Downloads:
            <a target="_blank" href="{% url 'newsite:download' 'latlon' %}">Co-Ordinates</a>,
            <a target="_blank" href="{% url 'newsite:download' 'gcell' %}">GCELL</a>
        </li>
    </ul>
</div>

<div class="progress" style="display: none;">
  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0"
  aria-valuemin="0" aria-valuemax="100" style="width:30%">
    30%
  </div>
</div>



<div class="alert alert-success fade in display_none">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>Gcell</strong>: <span id="success_message"> </span>
</div>

<p id="ajax_processing_message" class="lead display_none"><code> Please wait until success message  </code></p>

<form id="ioform" action="{% url 'newsite:io' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <table class="table-sm">
        <tr>
            <td>
                <label for="iofile" class="custom-file">
                    <input id="iofile" class="custom-file-input btn" type="file" name="{{ context.form.file.name }}">
                </label>
            </td>
             <td>
                <label for="id_type"> Type </label>
                    {{ context.form.type }}
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input id="submit_button" style="height: 100%" class="btn btn-primary" type="submit" value="Start Uploading" />
                <img id="upload_progress" class="display_none" alt="ajax_loader" src="{% static 'newsite/images/facebook.gif' %}" />
            </td>
        </tr>
    </table>
</form>

{% endblock %}

{% block additional_footer %}
    <!-- javascript -->
    <script src="{% static 'newsite/js/io.js' %}"></script>
    <script src="{% static 'newsite/js/lib/jquery-cookie.js' %}"></script>
    <script src="{% static 'newsite/js/lib/jquery.form.min.js' %}"></script>
{% endblock %}

newsite/templates/newsite/map-30thMay.html
{% extends "newsite/base.html" %}

{% load static %}

{% block additional_headers %}

    <link rel="stylesheet" type="text/css" href="{% static 'newsite/css/style.css' %}" />
    <script type="text/javascript">
        //global variable to be used from newsite.js script
        var NewSitePlan = {
            'ajax_url': '{% url "newsite:nearest-sites" %}',
            'static_url': '{% static "newsite/" %}'
        };
    </script>
{% endblock %}

{% block navigation %}

    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="{% url 'newsite:search' %}">Search</a></li>
        <li><a href="{% url 'newsite:about' %}">About</a></li>
       <li><a href="{% url 'newsite:io' %}">Import/Export</a></li>
        <li><a href="{% url 'newsite:rehome' %}">Rehome</a></li>
    </ul>

{% endblock %}

{% block container %}
    <form action="{% url 'newsite:new-site-plan' %}" method="post">
        {% csrf_token %}
        <table class="table table-hover">
            <thead class="thead-inverse">
                <tr> <th>CNP WR</th> <th>IPWave WR</th><th>Latitude</th><th>Longitude</th><th>Site</th><th>Nearest Site</th><th>Planned BSC</th><th>Planned LAC</th> <th>Distance ( miles )</th> </tr>
            </thead>
            <tbody table-hover>
                {% for ss in data %}
                <tr id="{{ ss.ipwavewr }}-{{ forloop.counter }}">
                    <td class="cnp_wr"> <input type="hidden" name="{{ form.cnp_wr.name }}" value="{{ ss.cnpwr }}"  >{{ ss.cnpwr }} </td>
                    <td class="ipwave_wr"> <input type="hidden" name="{{ form.ipwave_wr.name }}" value="{{ ss.ipwavewr }}"  > {{ ss.ipwavewr }} </td>
                    <td class="input_lat"> {{ ss.lat }} </td>
                    <td class="input_lon"> {{ ss.lon }} </td>
                    <td class="input_site"> <input type="hidden" name="{{ form.site.name }}" value="{{ ss.site }}" > {{ ss.site }} </td>
                    <td class="nearest_site"> {{ ss.nearest_site }} </td>
                    <td class="proposed_bsc"> <input type="hidden" name="{{ form.bsc.name }}" value="{{ ss.proposed_bsc }}"  > <span> {{ ss.proposed_bsc }} </span> </td>
                    <td class="proposed_lac"> <input type="hidden" name="{{ form.lac.name }}" value="{{ ss.proposed_lac }}"  > <span> {{ ss.proposed_lac }} </span> </td>
                    <td class="nearest_site_distance"> {{ ss.distance }} </td>
                    <td> <button name="{{ ss.ipwavewr }}-{{ forloop.counter }}" class="btn btn-default justify-individual-plan">Update </button> <img class="ajax_loader display_none" src="{% static 'newsite/images/facebook.gif' %}" /> </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="10"> <a href="{% url 'newsite:new-site-plan' %}"><input type="button" value="Upload another file" class="btn btn-link" /> </a>&nbsp; &nbsp; <input class="btn-primary btn" type="submit" value="Save and Download Plan" /></th>
                </tr>
            </tfoot>
        </table>
    </form>

    <div id="map"></div>
{% endblock %}

{% block additional_footer %}
    <!-- javascript -->
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGiluMgQFfw2abMSw4_KCEqNvxszjoQVk">
    </script>
    <script src="{% static 'newsite/js/map.js' %}"></script>
{% endblock %}

newsite/templates/newsite/map.html
{% extends "newsite/base.html" %}

{% load static %}

{% block additional_headers %}

    <link rel="stylesheet" type="text/css" href="{% static 'newsite/css/style.css' %}" />
    <script type="text/javascript">
        //global variable to be used from newsite.js script
        var NewSitePlan = {
            'ajax_url': '{% url "newsite:nearest-sites" %}',
            'static_url': '{% static "newsite/" %}'
        };
    </script>
{% endblock %}

{% block navigation %}

    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="{% url 'newsite:search' %}">Search</a></li>
        <li><a href="{% url 'newsite:about' %}">About</a></li>
       <li><a href="{% url 'newsite:io' %}">Import/Export</a></li>
        <li><a href="{% url 'newsite:rehome' %}">Rehome</a></li>
    </ul>

{% endblock %}

{% block container %}
    <form action="{% url 'newsite:new-site-plan' %}" method="post">
        {% csrf_token %}
        <table class="table table-hover">
            <thead class="thead-inverse">
                <tr> <th>CNP WR</th> <th>IPWave WR</th><th>Latitude</th><th>Longitude</th><th>Site</th><th>Nearest Site</th><th>Planned BSC</th><th>Planned LAC</th> <th>Distance ( miles )</th> </tr>
            </thead>
            <tbody table-hover>
                {% for ss in data %}
                <tr id="{{ ss.ipwavewr }}-{{ forloop.counter }}">
                    <td class="cnp_wr"> <input type="hidden" name="{{ form.cnp_wr.name }}" value="{{ ss.cnpwr }}"  >{{ ss.cnpwr }} </td>
                    <td class="ipwave_wr"> <input type="hidden" name="{{ form.ipwave_wr.name }}" value="{{ ss.ipwavewr }}"  > {{ ss.ipwavewr }} </td>
                    <td class="input_lat"> <input type="hidden" name="{{ form.lat.name }}" value="{{ ss.lat }}" > {{ ss.lat }} </td>
                    <td class="input_lon"> <input type="hidden" name="{{ form.lon.name }}" value="{{ ss.lon }}" > {{ ss.lon }} </td>
                    <td class="input_site"> <input type="hidden" name="{{ form.site.name }}" value="{{ ss.site }}" > {{ ss.site }} </td>
                    <td class="nearest_site"> {{ ss.nearest_site }} </td>
                    <td class="proposed_bsc"> <input type="hidden" name="{{ form.bsc.name }}" value="{{ ss.proposed_bsc }}"  > <span> {{ ss.proposed_bsc }} </span> </td>
                    <td class="proposed_lac"> <input type="hidden" name="{{ form.lac.name }}" value="{{ ss.proposed_lac }}"  > <span> {{ ss.proposed_lac }} </span> </td>
                    <td class="nearest_site_distance"> {{ ss.distance }} </td>
                    <td> <button name="{{ ss.ipwavewr }}-{{ forloop.counter }}" class="btn btn-default justify-individual-plan">Update </button> <img class="ajax_loader display_none" src="{% static 'newsite/images/facebook.gif' %}" /> </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="10"> <a href="{% url 'newsite:new-site-plan' %}"><input type="button" value="Upload another file" class="btn btn-link" /> </a>&nbsp; &nbsp; <input class="btn-primary btn" type="submit" value="Save and Download Plan" /></th>
                </tr>
            </tfoot>
        </table>
    </form>

    <div id="map"></div>
{% endblock %}

{% block additional_footer %}
    <!-- javascript -->
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGiluMgQFfw2abMSw4_KCEqNvxszjoQVk">
    </script>
    <script src="{% static 'newsite/js/map.js' %}"></script>
{% endblock %}

newsite/templates/newsite/navigation.html
<<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">2G Planning</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
   <!-- End Navbar -->