cnp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from log.forms import LoginForm

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^newsite/', include('newsite.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^nodeb/', include('nodeb.urls')),
    url(r'^process/', include('process.urls')),
    url(r'^igw/', include('igw.urls')),
    url(r'', include('log.urls')),
    url(r'^login/', auth_views.login, name='login', kwargs={'template_name': 'log/login.html', 'authentication_form': LoginForm}),
    url(r'^logout/', auth_views.logout, name='logout', kwargs={'next_page': '/login'} ),
]

igw/urls.py
from django.conf.urls import url
from .views import Dashboard, Ajax, IIG, IX, CDN, IO, IP


app_name = 'igw'
urlpatterns = [
    url(r'^$', Dashboard.as_view(), name='dashboard'),
    url(r'^ajax/$', Ajax.as_view(), name='ajax'),
    url(r'^iig/$', IIG.as_view(), name='iig'),
    url(r'^ix/$', IX.as_view(), name='ix'),
    url(r'^cdn/$', CDN.as_view(), name='cdn'),
    url(r'^io/$', IO.as_view(), name='io'),
    url(r'^ip/$', IP.as_view(), name='ip')
]

log/urls.py
from django.conf.urls import url
from .views import Home

app_name = 'log'

urlpatterns = [
    url(r'^$', Home.as_view(), name='home'),
]

newsite/urls.py
from django.conf.urls import url
from .views import NearestSites, NewSitePlan, About, ImportExport, Search, Dashboard, Rehome, Download

app_name = 'newsite'
urlpatterns = [
    url(r'^$', NewSitePlan.as_view(), name='new-site-plan'),
    url(r'^nearestsite/$', NearestSites.as_view(), name='nearest-sites'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^io/$', ImportExport.as_view(), name='io'),
    url(r'^search/$', Search.as_view(), name='search'),
    url(r'^dashboard/$', Dashboard.as_view(), name='dashboard'),
    url(r'^rehome/$', Rehome.as_view(), name='rehome'),
    url(r'^download/(?P<type>[a-z]+)/$', Download.as_view(), name='download')
]

nodeb/urls.py
from django.conf.urls import url
from .views import NodebPlan, ImportExport, NodebAjax, About, Search, Download

app_name = 'nodeb'
urlpatterns = [
    url(r'^$', NodebPlan.as_view(), name='nodeb-plan'),
    url(r'^nodebajax/$', NodebAjax.as_view(), name='nodebajax'),
    url(r'^io/$', ImportExport.as_view(), name='io'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^search/$', Search.as_view(), name='search'),
    url(r'^download/(?P<type>[a-z]+)/$', Download.as_view(), name='download')
]

report/urls.py
from django.conf.urls import url
from .views import HrTraffic, SummaryTraffic, ImportExport, Traffic, ThroughputVolume, NodeOvershoot, Throughput

app_name = 'report'
urlpatterns = [
    url(r'^hourlytraffic$', HrTraffic.as_view(), name='hourlytraffic'),
    url(r'^$', Traffic.as_view(), name='traffic'),
    url(r'^summarytraffic$', SummaryTraffic.as_view(), name='summarytraffic'),
    url(r'^io$', ImportExport.as_view(), name='io'),
    url(r'^volumetraffic$', ThroughputVolume.as_view(), name='volumetraffic'),
    url(r'^throughput$', Throughput.as_view(), name='throughput'),
    url(r'^overshoot$', NodeOvershoot.as_view(), name='overshoot'),
]

log/models.py
from django.db import models

# Create your models here.

log/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms

# If you don't do this you cannot use Bootstrap CSS
class LoginForm( AuthenticationForm ):
    username = forms.CharField(label="Username", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username', 'placeholder': 'Username'}))
    password = forms.CharField(label="Password", max_length=30, widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password', 'placeholder': 'Password'}))

log/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.
class Home(View):
    def get(self, request):
        context = {'title': 'Champions Never Panic'}
        return render(request, 'log/home.html', {'context': context})

log/templates/log/base.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <!-- Bootstrap styling -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'log/bootstrap3.3.7/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'log/bootstrap3.3.7/themes/sticky-footer-navbar/sticky-footer-navbar.css' %}" />
    <link rel="shortcut icon" href="{% static 'log/images/favicon.ico' %}" type="image/x-icon">
    <link href='http://fonts.googleapis.com/css?family=Merienda+One' rel='stylesheet' type='text/css'>
    <title>{{ context.title }}</title>

    {% block additional_headers %}
    {% endblock %}

</head>
    <!-- Begin page content -->
    <div class="container">
        {% block container %}
        {% endblock %}
    </div>


    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyright @ CNP, Grameenphone, 2018-2019</p>
      </div>
    </footer>

    {% block additional_footer %}
    {% endblock %}
    <!-- Bootstrap jquery file -->
    <script src="{% static 'log/bootstrap3.3.7/js/bootstrap.min.js' %}"></script>

  </body>

</html>

log/templates/log/home.html
{% extends "log/base.html" %}
{% load static %}

{% block additional_headers %}
     <link rel="stylesheet" type="text/css" href="{% static 'log/css/log.css' %}" />
{% endblock %}


{% block container %}
    <div class="page-header">
        <h3>Greetings from CNP Core Planning</h3>
    </div>

    <div class="sitemap_container">

        <div class="sitemap">
            <h4 class="comic">2G New Site Planning</h4>
            <ul>
                <li><a target="_blank" href="{% url 'newsite:new-site-plan' %}">Home</a></li>
                <li><a target="_blank" href="{% url 'newsite:search' %}">Search</a></li>
                <li><a target="_blank" href="{% url 'newsite:about' %}">About</a></li>
                <li><a target="_blank" href="{% url 'newsite:io' %}">Import/Export</a></li>
                <li><a target="_blank" href="{% url 'newsite:rehome' %}">Rehome</a></li>
            </ul>
        </div>

        <div class="sitemap">
            <h4 class="comic">3G New Site Planning</h4>
            <ul>
                <li><a target="_blank" href="{% url 'nodeb:nodeb-plan' %}">Home</a></li>
                <li><a target="_blank" href="{% url 'nodeb:search' %}">Search</a></li>
                <li><a target="_blank" href="{% url 'nodeb:about' %}">About</a></li>
                <li><a target="_blank" href="{% url 'nodeb:io' %}">Import/Export</a></li>
            </ul>
        </div>

        <div class="sitemap">
            <h4 class="comic">Reporting</h4>
            <ul>
                <li><a target="_blank" href="{% url 'report:hourlytraffic' %}">Hourly Traffic</a></li>
                <li><a target="_blank" href="{% url 'report:summarytraffic' %}">Summary Traffic</a></li>
                <li><a target="_blank" href="{% url 'report:volumetraffic' %}">Volume Traffic</a></li>
                <li><a target="_blank" href="{% url 'report:throughput' %}">Daily Traffic</a></li>
                <li><a target="_blank" href="{% url 'report:overshoot' %}"> Overshoots </a></li>
                <li><a target="_blank" href="{% url 'report:io' %}">Import/Export</a></li>
            </ul>
        </div>

        <div class="sitemap">
            <h4 class="comic">IGW Reporting</h4>
            <ul>
                <li><a target="_blank" href="{% url 'igw:dashboard' %}">Dashboard</a></li>
                <li><a target="_blank" href="{% url 'igw:iig' %}">IIG</a></li>
                <li><a target="_blank" href="{% url 'igw:ix' %}">BdIx & Novonix</a></li>
                <li><a target="_blank" href="{% url 'igw:io' %}">Import/Export</a></li>
            </ul>
        </div>

        <div class="sitemap">
            <h4 class="comic">Processors</h4>
            <ul>
                <li><a target="_blank" href="{% url 'process:mml-process' %}">MGW Overshoots Calculation</a></li>
                <li><a target="_blank" href="{% url 'process:citrix-process' %}">Ericsson Cell Data Preparing</a></li>
            </ul>
        </div>

    </div>

{% endblock %}

log/templates/log/login.html
{% extends "log/base.html" %}
{% load static %}

{% block container %}

    <div class="page-header">
        <h3>For login credentials, please communicate with CNP</h3>
    </div>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }}
            {{ form.password }}
        </div>


        <button type="submit" class="btn btn-primary">Login</button>
    </form>


{% endblock %}

log/templates/log/logout.html
{% extends "log/base.html" %}
{% load static %}

{% block container %}

 You have successfully logged out.



{% endblock %}